# Generated by Django 3.2.8 on 2021-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_plan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
